apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: businessdb
  name: businessdb
spec:
  selector:
    matchLabels:
      io.kompose.service: businessdb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: businessdb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: toor
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        image: mongo
        name: businessdb
        ports:
        - containerPort: 27017
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      volumes:
      - name: businessdb-claim0
        hostPath:
          path: /mnt/private/mongodb-business
status: {}
