apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: internaldb
  name: internaldb
spec:
  selector:
    matchLabels:
      io.kompose.service: internaldb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: internaldb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: toor
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        image: mongo
        name: internaldb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      volumes:
      - name: internaldb-claim0
        hostPath:
          path: /mnt/private/mongodb-internal
status: {}
