apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mongoapi
    io.kubernetes.replicas: 3
  name: mongoapi
spec:
  selector:
    matchLabels:
      io.kompose.service: mongoapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: mongoapi
    spec:
      containers:
      - image: 192.168.101.76:5000/mongoapi
        name: mongoapi
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
