apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: qos
  name: qos
spec:
  selector:
    matchLabels:
      io.kompose.service: qos
  strategy: {}
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: qos
    spec:
      containers:
      - image: registry:5000/loadbalancer
        name: loadbalancer
        ports:
        - containerPort: 8000
        resources: {}
      - image: registry:5000/autoscaler
        name: autoscaler
        resources: {}
      restartPolicy: Always
      nodeSelector:
        type: internalService
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "internalService"
          effect: "NoSchedule"
status: {}
